# Generated by Django 4.0.5 on 2022-06-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
